version: '3.8'

services:
  backend:
    build: .
    image: customer-satisfaction-backend
    ports:
      - "8080:8080"
    environment:
      - DAGSHUB_USER_TOKEN=${DAGSHUB_TOKEN}
    # Launches the FastAPI inference service
    command: python app.py

  frontend:
    build: .
    image: customer-satisfaction-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      # Match this to the os.getenv name in main_ui.py
      - BACKEND_SERVICE_URL=http://backend:8080/predict
    # Launches the Streamlit UI
    command: streamlit run main_ui.py