artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: "https://drive.google.com/file/d/1_M8ZzFem1uUnG6d3W_BDTA9B_ewYz0SQ/view?usp=sharing"
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/customer_data

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/customer_data
  STATUS_FILE: artifacts/data_validation/status.txt
  report_file: artifacts/data_validation/report.json
  raw_validated_dir: artifacts/data_validation/validated_data
  schema_path: schema.yaml
