name: AWS Production Deployment

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lint & Test
        run: echo "Linting and testing repository"

  build-and-push:
    name: Continuous Delivery
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::651045361628:role/github-oidc-ecr-role
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Backend
        run: |
          docker build -f Dockerfile \
            -t 651045361628.dkr.ecr.us-east-1.amazonaws.com/customer-satisfaction-backend:latest .
          docker push 651045361628.dkr.ecr.us-east-1.amazonaws.com/customer-satisfaction-backend:latest

      - name: Build & Push Frontend
        run: |
          docker build -f Dockerfile.frontend \
            -t 651045361628.dkr.ecr.us-east-1.amazonaws.com/customer-satisfaction-frontend:latest .
          docker push 651045361628.dkr.ecr.us-east-1.amazonaws.com/customer-satisfaction-frontend:latest

  deploy:
    name: Continuous Deployment
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy prometheus.yml to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "prometheus.yml"
          target: "/home/ec2-user/"

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            aws ecr get-login-password --region us-east-1 \
              | docker login --username AWS --password-stdin 651045361628.dkr.ecr.us-east-1.amazonaws.com

            docker network create ml-network || true

            docker pull 651045361628.dkr.ecr.us-east-1.amazonaws.com/customer-satisfaction-backend:latest
            docker pull 651045361628.dkr.ecr.us-east-1.amazonaws.com/customer-satisfaction-frontend:latest

            docker rm -f backend frontend prometheus grafana node-exporter || true

            docker run -d -p 8080:8080 --name backend --network ml-network \
              -e MLFLOW_TRACKING_URI=https://dagshub.com/Onabanjomicheal/Customer_Satisfaction_Prediction_to_Production.mlflow \
              -e MLFLOW_TRACKING_USERNAME=Onabanjomicheal \
              -e MLFLOW_TRACKING_PASSWORD=${{ secrets.MLFLOW_PASSWORD }} \
              -e DAGSHUB_TOKEN=${{ secrets.DAGSHUB_TOKEN }} \
              -e PYTHONPATH=/app/src \
              651045361628.dkr.ecr.us-east-1.amazonaws.com/customer-satisfaction-backend:latest

            TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" \
              -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
            PUBLIC_IP=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" \
              -s http://169.254.169.254/latest/meta-data/public-ipv4)

            docker run -d -p 8501:8501 --name frontend --network ml-network \
              -e BACKEND_SERVICE_URL=http://$PUBLIC_IP:8080/predict \
              651045361628.dkr.ecr.us-east-1.amazonaws.com/customer-satisfaction-frontend:latest

            docker run -d --name node-exporter --network ml-network -p 9100:9100 prom/node-exporter:latest
            docker run -d -p 9090:9090 --name prometheus --network ml-network \
              -v /home/ec2-user/prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus:latest
            docker run -d -p 3000:3000 --name grafana --network ml-network grafana/grafana:latest

            docker image prune -af
