name: AWS Production Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Lint & Test
        run: echo "Linting and testing repository"

  build-and-push:
    name: Continuous Delivery
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/customer-satisfaction-backend:latest -f Dockerfile .
          docker push ${{ steps.login-ecr.outputs.registry }}/customer-satisfaction-backend:latest
          docker build -t ${{ steps.login-ecr.outputs.registry }}/customer-satisfaction-frontend:latest -f Dockerfile.frontend .
          docker push ${{ steps.login-ecr.outputs.registry }}/customer-satisfaction-frontend:latest

  deploy:
    name: Continuous Deployment
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy prometheus.yml to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "prometheus.yml"
          target: "/home/ec2-user/"

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          use_insecure_cipher: true 
          script_stop: true
          script: |
            # 1. Login to ECR
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 651045361628.dkr.ecr.us-east-1.amazonaws.com

            # 2. Create network
            docker network create ml-network || true

            # 3. Pull images
            docker pull 651045361628.dkr.ecr.us-east-1.amazonaws.com/customer-satisfaction-backend:latest
            docker pull 651045361628.dkr.ecr.us-east-1.amazonaws.com/customer-satisfaction-frontend:latest

            # 4. Cleanup old containers
            docker rm -f backend frontend prometheus grafana node-exporter || true

            # 5. Run Backend
            docker run -d -p 8080:8080 --name backend --network ml-network \
              -e MLFLOW_TRACKING_URI=https://dagshub.com/Onabanjomicheal/Customer_Satisfaction_Prediction_to_Production.mlflow \
              -e MLFLOW_TRACKING_USERNAME=Onabanjomicheal \
              -e MLFLOW_TRACKING_PASSWORD=f1c60ac6579043df34bebaf39959b928ca4d6fd7 \
              -e DAGSHUB_TOKEN=f1c60ac6579043df34bebaf39959b928ca4d6fd7 \
              -e PYTHONPATH=/app/src \
              651045361628.dkr.ecr.us-east-1.amazonaws.com/customer-satisfaction-backend:latest

            # 6. Run Frontend (Automatically finds IP)
            TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
            PUBLIC_IP=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" -s http://169.254.169.254/latest/meta-data/public-ipv4)
            docker run -d -p 8501:8501 --name frontend --network ml-network \
              -e BACKEND_SERVICE_URL=http://$PUBLIC_IP:8080/predict \
              651045361628.dkr.ecr.us-east-1.amazonaws.com/customer-satisfaction-frontend:latest

            # 7. Run Monitoring
            docker run -d --name node-exporter --network ml-network -p 9100:9100 prom/node-exporter:latest
            docker run -d -p 9090:9090 --name prometheus --network ml-network -v /home/ec2-user/prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus:latest
            docker run -d -p 3000:3000 --name grafana --network ml-network grafana/grafana:latest

            # 8. Final Image Cleanup
            docker image prune -af